CREATE TABLE announcement (
      id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      date                DATE            NOT NULL,
      announcement_no     VARCHAR(50)     NOT NULL UNIQUE,
      title               VARCHAR(500)    NOT NULL,
      category_id         BIGINT,
      subcategory_id      BIGINT,
      issuer              VARCHAR(200),
      demander            VARCHAR(200),

      CONSTRAINT fk_announcement_date FOREIGN KEY (date) REFERENCES calendar_date(date) ON DELETE CASCADE,
      CONSTRAINT fk_announcement_category FOREIGN KEY (category_id) REFERENCES category(id),
      CONSTRAINT fk_announcement_subcategory FOREIGN KEY (subcategory_id) REFERENCES subcategory(id)
);