CREATE TABLE weather_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date                DATE            NOT NULL,
    weather_type        VARCHAR(10)     NOT NULL,
    max_temp            NUMERIC(5, 2),
    min_temp            NUMERIC(5, 2),
    precipitation       NUMERIC(6, 2)   DEFAULT 0,
    snow                NUMERIC(6, 2)   DEFAULT 0,
    humidity            NUMERIC(5, 2),
    daily_max_wind_speed   NUMERIC(5, 2),

    CONSTRAINT weather_date FOREIGN KEY (date) REFERENCES calendar_date(date) ON DELETE CASCADE
);